### ISSUE TITLE
通过和杨军和Alice的讨论，对于teamsedge管理平台创建账号的界面提出了修改意见，请帮忙处理，谢谢！

### ISSUE THREAD

**Issue by Tony-xbh** [CA17/TeamsACS#22]

**Comment by CarlDuFromChina** [comment]
@Tony-xbh 
开始时间是否是账号生效时间？
以下条目请帮忙解释一下含义：
工单编号
工单提交者
工单要求执行时间

账号状态“其它”指的是？

**Comment by Tony-xbh** [comment]
开始时间是否是账号生效时间？   是的

以下条目请帮忙解释一下含义：
工单编号：指每个需求都要对应一个相应的工单
工单提交者：指是谁提交了业务需求
工单要求执行时间：指提出的工单需要在有效的时间内完成


账号状态“其它”指的是？   目前没有定义，杨军讲先添加这一条

________________________________
发件人: Karl Du ***@***.***>
发送时间: 2023年10月25日 20:55
收件人: CA17/TeamsACS ***@***.***>
抄送: Tony Xu 徐宝华 ***@***.***>; Mention ***@***.***>
主题: Re: [CA17/TeamsACS] 通过和杨军和Alice的讨论，对于teamsedge管理平台创建账号的界面提出了修改意见，请帮忙处理，谢谢！ (Issue #22)


@Tony-xbh<https://github.com/Tony-xbh>
开始时间是否是账号生效时间？
以下条目请帮忙解释一下含义：
工单编号
工单提交者
工单要求执行时间

账号状态“其它”指的是？

―
